version: "3"
services:
  backend:
    build: ./server
    image: sonuchapter247/test-backend:latest
    ports:
      - "8000:8000"
  frontend:
    build: ./ui
    image: sonuchapter247/test-ui:latest
    ports:
      - "8001:80"
